{{- range $broker := $.Values.brokers}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" $ }}-{{ $broker.id }}
  labels: {{- include "kafka.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "kafka.name" $ }}-{{ $broker.id }}
    app.kubernetes.io/component: kafka
spec:
  ports:
    {{- range $listenerPort := $.Values.listenerPorts }}
    - port: {{ $listenerPort.port }}
      name: {{ $listenerPort.name }}
    {{- end }}
    {{- if $.Values.prometheus.jmx.enabled }}
    - port: {{ $.Values.prometheus.jmx.port }}
      name: metrics
    {{- end }}
  selector: {{- include "kafka.labels.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "kafka.name" $ }}-{{ $broker.id }}
    app.kubernetes.io/component: kafka
{{- end }}
