apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}
  labels: {{- include "kafka.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  ports:
    - port: 9092
      name: broker
    {{- if .Values.prometheus.jmx.enabled }}
    - port: {{ .Values.prometheus.jmx.port }}
      name: metrics
    {{- end }}
  selector: {{- include "kafka.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
